### ISSUE TITLE
numeric.T.exp does not work

### ISSUE THREAD

**Issue by jgbos** [sloisel/numeric#41]
Receive the following error when attempting to use the "exp" function on a complex array:

> > a = numeric.fft(0,1)
> > {x: 0, y: 1}
> > a.exp()
> > ReferenceError: exp is not defined
> >     at Object.eval [as exp](eval at <anonymous> %28/Users/foo/math/node_modules/numeric/numeric-1.2.6.js:746:26%29, <anonymous>:2:34)
> >     at eval (eval at Tunop (/Users/foo/projects/math/node_modules/numeric/numeric-1.2.6.js:1101:12), <anonymous>:3:18)
> >     at repl:1:2
> >     at REPLServer.self.eval (repl.js:110:21)
> >     at Interface.<anonymous> (repl.js:239:12)
> >     at Interface.EventEmitter.emit (events.js:95:17)
> >     at Interface._onLine (readline.js:202:10)
> >     at Interface.<anonymous> (readline.js:322:12)
> >     at Array.forEach (native)
> >     at Interface._normalWrite (readline.js:321:11)

**Comment by eoinmurray** [comment]
Yes I get same error it seems T.exp is documented, but not implemented.

**Comment by sloisel** [comment]
Another bug. Real world has imposed a backlog of those. Thanks,
